apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "stroom.gchq.github.io/v1",
          "kind": "DatabaseServer",
          "metadata": {
            "name": "dev",
            "namespace": "stroom-7"
          },
          "spec": {
            "additionalConfig": [],
            "affinity": {},
            "backup": {
              "databaseNames": [
                "stroom",
                "stats"
              ],
              "schedule": "*/5 * * * *",
              "volume": {
                "nfs": {
                  "path": "/volume2/stroom",
                  "server": "gs-fs01.internal"
                }
              }
            },
            "databaseNames": [
              "stroom",
              "stats"
            ],
            "image": {
              "repository": "mysql/mysql-server",
              "tag": "8.0.23"
            },
            "livenessProbeTimings": {
              "failureThreshold": 10,
              "initialDelaySeconds": 5,
              "periodSeconds": 1,
              "successThreshold": 1,
              "timeoutSeconds": 5
            },
            "nodeSelector": {},
            "podAnnotations": {},
            "podSecurityContext": {},
            "readinessProbeTimings": {
              "failureThreshold": 10,
              "initialDelaySeconds": 5,
              "periodSeconds": 1,
              "successThreshold": 1,
              "timeoutSeconds": 5
            },
            "resources": {
              "limits": {
                "cpu": "500m",
                "memory": "500Mi"
              },
              "requests": {
                "cpu": "100m",
                "memory": "100Mi"
              }
            },
            "securityContext": {},
            "tolerations": [],
            "volumeClaim": {
              "accessModes": [
                "ReadWriteOnce"
              ],
              "resources": {
                "limits": {
                  "storage": "200Mi"
                },
                "requests": {
                  "storage": "100Mi"
                }
              },
              "storageClassName": "",
              "volumeName": "stroom-db"
            }
          }
        },
        {
          "apiVersion": "stroom.gchq.github.io/v1",
          "kind": "StroomCluster",
          "metadata": {
            "name": "dev",
            "namespace": "stroom-7"
          },
          "spec": {
            "appDatabaseRef": {
              "databaseName": "stroom",
              "databaseServerRef": {
                "name": "dev"
              }
            },
            "configMapName": "stroom-dev",
            "extraEnv": [],
            "image": {
              "repository": "docker.intranet.gradata.com.au/gchq/stroom",
              "tag": "v7"
            },
            "imagePullPolicy": "Always",
            "ingress": {
              "hostName": "stroom-7.internal",
              "secretName": "stroom-7-tls"
            },
            "nodeSets": [
              {
                "affinity": {},
                "count": 2,
                "ingressEnabled": true,
                "livenessProbeTimings": {},
                "localDataVolumeClaim": {
                  "accessModes": [
                    "ReadWriteOnce"
                  ],
                  "resources": {
                    "limits": {
                      "storage": "1Gi"
                    },
                    "requests": {
                      "storage": "1Gi"
                    }
                  },
                  "selector": {
                    "matchLabels": {
                      "app": "stroom-7",
                      "component": "stroom-node"
                    }
                  },
                  "storageClassName": ""
                },
                "name": "data",
                "nodeSelector": {},
                "podAnnotations": {},
                "podSecurityContext": {},
                "resources": {
                  "limits": {
                    "cpu": "2",
                    "memory": "8Gi"
                  },
                  "requests": {
                    "cpu": "500m",
                    "memory": "2Gi"
                  }
                },
                "role": "Processing",
                "securityContext": {},
                "sharedDataVolume": {
                  "nfs": {
                    "path": "/volume2/AppData/stroom-7/stroom-shared",
                    "server": "gs-fs01.internal"
                  }
                },
                "startupProbeTimings": {},
                "tolerations": []
              },
              {
                "count": 1,
                "ingressEnabled": true,
                "localDataVolumeClaim": {
                  "accessModes": [
                    "ReadWriteOnce"
                  ],
                  "resources": {
                    "limits": {
                      "storage": "1Gi"
                    },
                    "requests": {
                      "storage": "1Gi"
                    }
                  },
                  "selector": {
                    "matchLabels": {
                      "app": "stroom-7",
                      "component": "stroom-node"
                    }
                  },
                  "storageClassName": ""
                },
                "name": "ui",
                "resources": {
                  "limits": {
                    "cpu": "2",
                    "memory": "4Gi"
                  },
                  "requests": {
                    "cpu": "500m",
                    "memory": "2Gi"
                  }
                },
                "role": "Frontend"
              }
            ],
            "statsDatabaseRef": {
              "databaseName": "stats",
              "databaseServerRef": {
                "name": "dev"
              }
            }
          }
        },
        {
          "apiVersion": "stroom.gchq.github.io/v1",
          "kind": "StroomTaskAutoscaler",
          "metadata": {
            "name": "dev"
          },
          "spec": {
            "stroomClusterRef": {
              "name": "dev"
            }
          }
        }
      ]
    capabilities: Auto Pilot
    operators.operatorframework.io/builder: operator-sdk-v1.8.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: stroom-k8s-operator.v0.0.15
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DatabaseServer is the Schema for the databases API
      displayName: Database Server
      kind: DatabaseServer
      name: databaseservers.stroom.gchq.github.io
      version: v1
    - description: StroomCluster is the Schema for the stroomclusters API
      displayName: Stroom Cluster
      kind: StroomCluster
      name: stroomclusters.stroom.gchq.github.io
      version: v1
    - description: StroomTaskAutoscaler is the Schema for the stroomtaskautoscalers
        API
      displayName: Stroom Task Autoscaler
      kind: StroomTaskAutoscaler
      name: stroomtaskautoscalers.stroom.gchq.github.io
      version: v1
  description: Kubernetes operator for deploying and managing a Stroom cluster
  displayName: stroom-k8s-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - metrics.k8s.io
          resources:
          - pods
          verbs:
          - get
          - list
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - databaseservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - databaseservers/finalizers
          verbs:
          - update
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - databaseservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - stroomclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - stroomclusters/finalizers
          verbs:
          - update
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - stroomclusters/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - stroomtaskautoscalers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - stroomtaskautoscalers/finalizers
          verbs:
          - update
        - apiGroups:
          - stroom.gchq.github.io
          resources:
          - stroomtaskautoscalers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: stroom-operator-controller-manager
      deployments:
      - name: stroom-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: docker.intranet.gradata.com.au/gchq.github.io/stroom-k8s-operator-bundle:v0.0.15
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 50Mi
                securityContext:
                  allowPrivilegeEscalation: false
              serviceAccountName: stroom-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: stroom-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - stroom
  links:
  - name: Repository (GitHub)
    url: https://github.com/p-kimberley/stroom-k8s-operator
  - name: Stroom repository (GitHub)
    url: https://github.com/gchq/stroom
  maintainers:
  - email: peter@gradata.com.au
    name: Peter Kimberley
  maturity: beta
  provider:
    name: GCHQ
  version: 0.0.15
