# permissions for end users to edit databasebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasebackup-editor-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/status
  verbs:
  - get
