
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databasebackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - databaseservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers/status
  verbs:
  - get
  - patch
  - update
