
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/finalizers
  verbs:
  - update
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/status
  verbs:
  - get
  - patch
  - update
