# permissions for end users to edit stroomtaskautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroomtaskautoscaler-editor-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers/status
  verbs:
  - get
