# permissions for end users to view stroomclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroomcluster-viewer-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/status
  verbs:
  - get
