# permissions for end users to edit stroomclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroomcluster-editor-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomclusters/status
  verbs:
  - get
