# permissions for end users to view stroomtaskautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stroomtaskautoscaler-viewer-role
rules:
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stroom.gchq.github.io
  resources:
  - stroomtaskautoscalers/status
  verbs:
  - get
