apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Auto Pilot
  name: stroom-k8s-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DatabaseServer is the Schema for the databases API
      displayName: Database Server
      kind: DatabaseServer
      name: databaseservers.stroom.gchq.github.io
      version: v1
    - description: StroomCluster is the Schema for the stroomclusters API
      displayName: Stroom Cluster
      kind: StroomCluster
      name: stroomclusters.stroom.gchq.github.io
      version: v1
    - description: StroomTaskAutoscaler is the Schema for the stroomtaskautoscalers
        API
      displayName: Stroom Task Autoscaler
      kind: StroomTaskAutoscaler
      name: stroomtaskautoscalers.stroom.gchq.github.io
      version: v1
  description: Kubernetes operator for deploying and managing a Stroom cluster
  displayName: stroom-k8s-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - stroom
  links:
  - name: Repository (GitHub)
    url: https://github.com/gradata-systems/stroom-k8s-operator
  - name: Stroom repository (GitHub)
    url: https://github.com/gchq/stroom
  maintainers:
  - email: peter@gradata.com.au
    name: Peter Kimberley
  maturity: beta
  provider:
    name: Gradata Systems Pty Ltd
  version: 1.0.0
