## Append samples you want in your CSV to this file as resources ##
resources:
- stroom_v1_stroomcluster.yaml
- stroom_v1_databaseserver.yaml
- stroom_v1_stroomtaskautoscaler.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
