apiVersion: stroom.gchq.github.io/v1
kind: StroomCluster
metadata:
  name: dev
  namespace: stroom-7
spec:
  image:
    repository: gchq/stroom
    tag: v7.0-LATEST
  imagePullPolicy: Always
  extraEnv: []
  configMapRef:
    name: stroom-dev
  databaseServerRef:
    serverRef:
      name: dev
#    serverAddress:
#      host: mysql.example.com
#      port: 3306
#      secretName: mysql-stroomuser-password
  appDatabaseName: stroom
  statsDatabaseName: stats
  nodeTerminationPeriodSecs: 300
  ingress:
    hostName: stroom-7.example.com
    secretName: stroom-7-tls

  nodeSets:
    - name: data
      count: 2
      role: Processing
      localDataVolumeClaim:
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
          limits:
            storage: 1Gi
        selector:
          matchLabels:
            app: stroom-7
            component: stroom-node
      sharedDataVolume:
        nfs:
          server: fs.example.org
          path: /data/stroom-shared
      ingressEnabled: true
      readinessProbeTimings: {}
      livenessProbeTimings: {}
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 8Gi
      podAnnotations: {}
      podSecurityContext: {}
      securityContext: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
    - name: ui
      count: 1
      role: Frontend
      localDataVolumeClaim:
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
          limits:
            storage: 1Gi
        selector:
          matchLabels:
            app: stroom-7
            component: stroom-node
      sharedDataVolume:
        nfs:
          server: fs.example.org
          path: /data/stroom-shared
      ingressEnabled: true
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 4Gi