apiVersion: stroom.gchq.github.io/v1
kind: StroomCluster
metadata:
  name: dev
spec:
  image:
    repository: gchq/stroom
    tag: v7
  extraEnv: {}
  configMapName: ""
  appDatabaseRef: {}
  statsDatabaseRef: {}
  ingress:
    hostName: ""
    secretName: ""
    className: nginx

  nodeSets:
    - name: data
      count: 3
      role: Processing # Processing | Frontend
      localData:
        volumeClaim: {} # VolumeClaim
      sharedData:
        volume: {} # Volume
      startupProbeTimings: {} # ProbeTimings
      livenessProbeTimings: {} # ProbeTimings
      resources: {}
      podAnnotations: {}
      podSecurityContext: {}
      securityContext: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
    - name: ui
      count: 2
      role: Frontend