apiVersion: stroom.gchq.github.io/v1
kind: DatabaseBackup
metadata:
  name: dev
  namespace: stroom
spec:
  image:
    repository: mysql/mysql-server
    tag: 8.0.26
  schedule: "*/5 * * * *"
  databaseServerRef:
    serverRef:
      name: dev
    serverAddress:
      host: mysql.example.com
      port: 3306
      secretName: stroom-dev-db
  databaseNames:
    - stroom
    - stats
  volume:
    nfs:
      path: /data/stroom
      server: backup.fs.example.com