apiVersion: stroom.gchq.github.io/v1
kind: DatabaseServer
metadata:
  name: dev
  namespace: stroom
spec:
  image:
    repository: mysql/mysql-server
    tag: 8.0.25
  databaseNames:
    - stroom
    - stats
  additionalConfig: []
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  volumeClaim:
    volumeName: stroom-db
    accessModes:
      - ReadWriteOnce
    storageClassName: ""
    resources:
      requests:
        storage: 200Mi
      limits:
        storage: 500Mi
  backup:
    schedule: "*/5 * * * *"
    databaseNames:
      - stroom
      - stats
    volume:
      nfs:
        path: /data/stroom
        server: backup.fs.example.com
